export const COMPANY_DATA = {
  'sure-luxury-homes': {
    name: 'Sure Luxury Homes',
    logo: '/assets/logo3.png',
    location: 'Victoria Island, Lagos',
    phone: '+234 801 234 5678',
    email: 'contact@sureluxuryhomes.com',
    website: 'www.sureluxuryhomes.com',
    description: 'Premier luxury real estate company specializing in high-end properties across Lagos. With over a decade of experience, we offer exclusive access to some of the most prestigious properties in prime locations.',
    propertiesCount: 156,
    properties: [
      {
        id: 'slh1',
        title: 'Luxury 5 Bedroom Mansion',
        type: 'Mansion for sale',
        price: 850000000,
        location: 'Banana Island, Lagos',
        bedrooms: 5,
        bathrooms: 6,
        parkingSpaces: 4,
        images: ['/assets/3.jpg'],
      },
      {
        id: 'slh2',
        title: 'Waterfront 6 Bedroom Villa',
        type: 'Villa for sale',
        price: 950000000,
        location: 'Banana Island, Lagos',
        bedrooms: 6,
        bathrooms: 7,
        parkingSpaces: 5,
        images: ['/assets/5.jpg'],
      },
      {
        id: 'slh3',
        title: 'Premium 4 Bedroom Penthouse',
        type: 'Penthouse for sale',
        price: 650000000,
        location: 'Victoria Island, Lagos',
        bedrooms: 4,
        bathrooms: 5,
        parkingSpaces: 3,
        images: ['/assets/7.jpg'],
      },
      {
        id: 'slh4',
        title: 'Luxury 3 Bedroom Apartment',
        type: 'Apartment for sale',
        price: 450000000,
        location: 'Ikoyi, Lagos',
        bedrooms: 3,
        bathrooms: 4,
        parkingSpaces: 2,
        images: ['/assets/8.jpg'],
      }
    ]
  },
  'bluehedge-realtors': {
    name: 'BlueHedge Realtors',
    logo: '/assets/logo2.png',
    location: 'Lekki Phase 1, Lagos',
    phone: '+234 802 345 6789',
    email: 'info@bluehedgerealtors.com',
    website: 'www.bluehedgerealtors.com',
    description: 'A leading real estate agency known for exceptional service and market expertise. We help clients find their perfect property while ensuring a smooth and transparent transaction process.',
    propertiesCount: 89,
    properties: [
      {
        id: 'bhr1',
        title: '4 Bedroom Penthouse',
        type: 'Penthouse for sale',
        price: 450000000,
        location: 'Lekki Phase 1, Lagos',
        bedrooms: 4,
        bathrooms: 5,
        parkingSpaces: 2,
        images: ['/assets/1.jpg'],
      },
      {
        id: 'bhr2',
        title: 'Modern 3 Bedroom Apartment',
        type: 'Apartment for rent',
        price: 15000000,
        location: 'Lekki Phase 1, Lagos',
        bedrooms: 3,
        bathrooms: 3,
        parkingSpaces: 2,
        images: ['/assets/2.jpg'],
      },
      {
        id: 'bhr3',
        title: '5 Bedroom Detached House',
        type: 'House for sale',
        price: 380000000,
        location: 'Chevron Drive, Lagos',
        bedrooms: 5,
        bathrooms: 5,
        parkingSpaces: 3,
        images: ['/assets/4.jpg'],
      }
    ]
  },
  'shelter-nest-realty': {
    name: 'Shelter Nest Realty',
    logo: '/assets/logo5.jpg',
    location: 'Ikoyi, Lagos',
    phone: '+234 803 456 7890',
    email: 'hello@shelternest.com',
    website: 'www.shelternest.com',
    description: 'Your trusted partner in finding the perfect home. We specialize in residential properties across Lagos, offering personalized service and deep market insights.',
    propertiesCount: 124,
    properties: [
      {
        id: 'snr1',
        title: '3 Bedroom Luxury Apartment',
        type: 'Apartment for sale',
        price: 280000000,
        location: 'Ikoyi, Lagos',
        bedrooms: 3,
        bathrooms: 4,
        parkingSpaces: 2,
        images: ['/assets/2.jpg'],
      },
      {
        id: 'snr2',
        title: '4 Bedroom Terrace House',
        type: 'Terrace for sale',
        price: 320000000,
        location: 'Osborne, Ikoyi',
        bedrooms: 4,
        bathrooms: 4,
        parkingSpaces: 2,
        images: ['/assets/6.jpg'],
      },
      {
        id: 'snr3',
        title: '2 Bedroom Serviced Apartment',
        type: 'Apartment for rent',
        price: 12000000,
        location: 'Parkview Estate, Ikoyi',
        bedrooms: 2,
        bathrooms: 2,
        parkingSpaces: 1,
        images: ['/assets/3.jpg'],
      },
      {
        id: 'snr4',
        title: '5 Bedroom Detached House',
        type: 'House for sale',
        price: 550000000,
        location: 'Banana Island, Ikoyi',
        bedrooms: 5,
        bathrooms: 6,
        parkingSpaces: 4,
        images: ['/assets/7.jpg'],
      }
    ]
  },
  'urban-prime-realty': {
    name: 'Urban Prime Realty',
    logo: '/assets/logo1.png',
    location: 'Maryland, Lagos',
    phone: '+234 804 567 8901',
    email: 'contact@urbanprime.com',
    website: 'www.urbanprime.com',
    description: 'Modern real estate solutions for the urban professional. We focus on contemporary properties in prime locations, offering both sales and rental options.',
    propertiesCount: 98,
    properties: [
      {
        id: 'upr1',
        title: 'Modern 4 Bedroom Townhouse',
        type: 'Townhouse for sale',
        price: 320000000,
        location: 'Maryland, Lagos',
        bedrooms: 4,
        bathrooms: 4,
        parkingSpaces: 2,
        images: ['/assets/4.jpg'],
      },
      {
        id: 'upr2',
        title: '3 Bedroom Smart Home',
        type: 'Apartment for sale',
        price: 250000000,
        location: 'Magodo GRA, Lagos',
        bedrooms: 3,
        bathrooms: 3,
        parkingSpaces: 2,
        images: ['/assets/1.jpg'],
      },
      {
        id: 'upr3',
        title: '2 Bedroom Studio Apartment',
        type: 'Apartment for rent',
        price: 8000000,
        location: 'Ikeja GRA, Lagos',
        bedrooms: 2,
        bathrooms: 2,
        parkingSpaces: 1,
        images: ['/assets/5.jpg'],
      },
      {
        id: 'upr4',
        title: '4 Bedroom Semi-Detached',
        type: 'House for sale',
        price: 280000000,
        location: 'Omole Phase 1, Lagos',
        bedrooms: 4,
        bathrooms: 4,
        parkingSpaces: 2,
        images: ['/assets/8.jpg'],
      }
    ]
  }
} as const

export type CompanySlug = keyof typeof COMPANY_DATA
